export interface IGlobalMocksObject {
  AdSense?: Partial<GoogleAppsScript.Adsense>,
  AdminDirectory?: Partial<GoogleAppsScript.AdminDirectory>,
  AdminGroupsMigration?: Partial<GoogleAppsScript.AdminGroupsMigration>,
  AdminGroupsSettings?: Partial<GoogleAppsScript.AdminGroupsSettings>,
  AdminLicenseManager?: Partial<GoogleAppsScript.AdminLicenseManager>,
  AdminReports?: Partial<GoogleAppsScript.AdminReports>,
  AdminReseller?: Partial<GoogleAppsScript.AdminReseller>,
  Analytics?: Partial<GoogleAppsScript.Analytics>,
  AnalyticsReporting?: Partial<GoogleAppsScript.AnalyticsReporting>,
  AppsActivity?: Partial<GoogleAppsScript.Appsactivity>,
  BigQuery?: Partial<GoogleAppsScript.BigQuery>,
  Browser?: Partial<GoogleAppsScript.Base.Browser>,
  CacheService?: Partial<GoogleAppsScript.Cache.CacheService>,
  Calendar?: Partial<GoogleAppsScript.Calendar.Calendar>,
  CalendarApp?: Partial<GoogleAppsScript.Calendar.CalendarApp>,
  CardService?: Partial<GoogleAppsScript.Card_Service.CardService>,
  Charts?: Partial<GoogleAppsScript.Charts.Charts>,
  Classroom?: Partial<GoogleAppsScript.Classroom>,
  ConferenceDataService?: Partial<GoogleAppsScript.Conference_Data.ConferenceDataService>,
  ContactsApp?: Partial<GoogleAppsScript.Contacts.ContactsApp>,
  ContentService?: Partial<GoogleAppsScript.Content.ContentService>,
  DataStudioApp?: Partial<GoogleAppsScript.Data_Studio.DataStudioApp>,
  Docs?: Partial<GoogleAppsScript.Docs>,
  DocumentApp?: Partial<GoogleAppsScript.Document.DocumentApp>,
  Drive?: Partial<GoogleAppsScript.Drive>,
  DriveActivity?: Partial<GoogleAppsScript.DriveActivity>,
  DriveApp?: Partial<GoogleAppsScript.Drive.DriveApp>,
  FormApp?: Partial<GoogleAppsScript.Forms.FormApp>,
  GmailApp?: Partial<GoogleAppsScript.Gmail.GmailApp>,
  GroupsApp?: Partial<GoogleAppsScript.Groups.GroupsApp>,
  HtmlService?: Partial<GoogleAppsScript.HTML.HtmlService>,
  Jdbc?: Partial<GoogleAppsScript.JDBC.Jdbc>,
  LanguageApp?: Partial<GoogleAppsScript.Language.LanguageApp>,
  LinearOptimizationService?: Partial<GoogleAppsScript.Optimization.LinearOptimizationService>,
  LockService?: Partial<GoogleAppsScript.Lock.LockService>,
  Logger?: Partial<GoogleAppsScript.Base.Logger>,
  MailApp?: Partial<GoogleAppsScript.Mail.MailApp>,
  Maps?: Partial<GoogleAppsScript.Maps.Maps>,
  Mirror?: Partial<GoogleAppsScript.Mirror>,
  People?: Partial<GoogleAppsScript.People>,
  PropertiesService?: Partial<GoogleAppsScript.Properties.PropertiesService>,
  ScriptApp?: Partial<GoogleAppsScript.Script.ScriptApp>,
  Session?: Partial<GoogleAppsScript.Base.Session>,
  Sheets?: Partial<GoogleAppsScript.Sheets>,
  SitesApp?: Partial<GoogleAppsScript.Sites.SitesApp>,
  Slides?: Partial<GoogleAppsScript.Slides>,
  SlidesApp?: Partial<GoogleAppsScript.Slides.SlidesApp>,
  SpreadsheetApp?: Partial<GoogleAppsScript.Spreadsheet.SpreadsheetApp>,
  TagManager?: Partial<GoogleAppsScript.TagManager>,
  Tasks?: Partial<GoogleAppsScript.Tasks>,
  UrlFetchApp?: Partial<GoogleAppsScript.URL_Fetch.UrlFetchApp>,
  Utilities?: Partial<GoogleAppsScript.Utilities.Utilities>,
  XmlService?: Partial<GoogleAppsScript.XML_Service.XmlService>,
  YouTube?: Partial<GoogleAppsScript.YouTube>,
  YouTubeAnalytics?: Partial<GoogleAppsScript.YouTubeAnalytics>,
}
export const DefaultGlobalMocks: IGlobalMocksObject = {
  Logger: {
    log: (data: any) => {
      console.log(data)
      return Logger
    },
    clear: () => undefined,
    getLog: () => ''
  }
}
